//
//  DilloDayStyleKit.h
//  Dillo Day
//
//  Created by Philip Meyers IV on 4/14/15.
//  Copyright (c) 2015 Mayfest. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface DilloDayStyleKit : NSObject

// Colors
+ (UIColor*)tabBarColor;
+ (UIColor*)tabBarUnselectedColor;
+ (UIColor*)tabBarSelectedColor;
+ (UIColor*)navigationBarColor;
+ (UIColor*)navigationBarTextColor;
+ (UIColor*)barButtonItemColor;
+ (UIColor*)barButtonItemHighlightedColor;
+ (UIColor*)notificationCellBackgroundColor;
+ (UIColor*)notificationIconColor;
+ (UIColor*)fontColor;

// Drawing Methods
+ (void)drawHelpIconWithFrame: (CGRect)frame;
+ (void)drawNotificationsIcon;
+ (void)drawMapIcon;
+ (void)drawLineupIcon;

@end
