//
//  DilloDayStyleKit.h
//  Dillo Day
//
//  Created by Philip Meyers IV on 4/7/15.
//  Copyright (c) 2015 Mayfest. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface DilloDayStyleKit : NSObject

// Colors
+ (UIColor*)tabBarColor;
+ (UIColor*)tabBarUnselectedTextColor;
+ (UIColor*)tabBarSelectedTextColor;
+ (UIColor*)navigationBarColor;
+ (UIColor*)navigationBarTextColor;
+ (UIColor*)barButtonItemColor;
+ (UIColor*)barButtonItemHighlightedColor;

// Drawing Methods
+ (void)drawCanvas1;

@end
