//
//  DilloDayStyleKit.m
//  Dillo Day
//
//  Created by Philip Meyers IV on 4/7/15.
//  Copyright (c) 2015 Mayfest. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "DilloDayStyleKit.h"


@implementation DilloDayStyleKit

#pragma mark Cache

static UIColor* _tabBarColor = nil;
static UIColor* _tabBarUnselectedTextColor = nil;
static UIColor* _tabBarSelectedTextColor = nil;
static UIColor* _navigationBarColor = nil;
static UIColor* _navigationBarTextColor = nil;
static UIColor* _barButtonItemColor = nil;
static UIColor* _barButtonItemHighlightedColor = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _tabBarColor = [UIColor colorWithRed: 0.102 green: 0.737 blue: 0.612 alpha: 1];
    CGFloat tabBarColorHSBA[4];
    [_tabBarColor getHue: &tabBarColorHSBA[0] saturation: &tabBarColorHSBA[1] brightness: &tabBarColorHSBA[2] alpha: &tabBarColorHSBA[3]];

    _tabBarUnselectedTextColor = [UIColor colorWithHue: tabBarColorHSBA[0] saturation: tabBarColorHSBA[1] brightness: 0.4 alpha: tabBarColorHSBA[3]];
    _navigationBarColor = DilloDayStyleKit.tabBarColor;
    _tabBarSelectedTextColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    _navigationBarTextColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    _barButtonItemColor = [UIColor colorWithRed: 0.204 green: 0.596 blue: 0.859 alpha: 1];
    CGFloat barButtonItemColorHSBA[4];
    [_barButtonItemColor getHue: &barButtonItemColorHSBA[0] saturation: &barButtonItemColorHSBA[1] brightness: &barButtonItemColorHSBA[2] alpha: &barButtonItemColorHSBA[3]];

    _barButtonItemHighlightedColor = [UIColor colorWithHue: barButtonItemColorHSBA[0] saturation: barButtonItemColorHSBA[1] brightness: 1 alpha: barButtonItemColorHSBA[3]];

}

#pragma mark Colors

+ (UIColor*)tabBarColor { return _tabBarColor; }
+ (UIColor*)tabBarUnselectedTextColor { return _tabBarUnselectedTextColor; }
+ (UIColor*)tabBarSelectedTextColor { return _tabBarSelectedTextColor; }
+ (UIColor*)navigationBarColor { return _navigationBarColor; }
+ (UIColor*)navigationBarTextColor { return _navigationBarTextColor; }
+ (UIColor*)barButtonItemColor { return _barButtonItemColor; }
+ (UIColor*)barButtonItemHighlightedColor { return _barButtonItemHighlightedColor; }

#pragma mark Drawing Methods

+ (void)drawCanvas1
{
}

@end
